import {
  componentFactoryWithUniformPersonalizer
} from '@uniformdev/esi-jss-react';
/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import Hero from "./components/Hero/Hero";
import LinkList from "./components/LinkList/LinkList";

const components = new Map();
components.set("Hero", Hero);
components.set("LinkList", LinkList);

export default componentFactoryWithUniformPersonalizer(function componentFactory(componentName) {
    return components.get(componentName);
})
